const tap = require('tap');
const whatype = require('./index');

// whatype function
tap.equal(whatype(''), 'string');
tap.equal(whatype('whatever'), 'string');
tap.equal(whatype(new String('foo')), 'string');
tap.equal(whatype(null), 'null');
tap.equal(whatype(undefined), 'undefined');
tap.equal(whatype(NaN), 'not-a-number');
tap.equal(whatype(0), 'number');
tap.equal(whatype(42), 'number');
tap.equal(whatype(30.5), 'number');
tap.equal(whatype(-17), 'number');
tap.equal(whatype(new Number('12')), 'number');
tap.equal(whatype(true), 'boolean');
tap.equal(whatype(false), 'boolean');
tap.equal(whatype(new Boolean(1)), 'boolean');
tap.equal(whatype(function() { return arguments; }()), 'arguments');
tap.equal(whatype(Infinity), 'infinity');
tap.equal(whatype(-Infinity), '-infinity');
tap.equal(whatype({}), 'object');
tap.equal(whatype({ a: 123 }), 'object');
tap.equal(whatype(/\d/), 'regexp');
tap.equal(whatype([]), 'array');
tap.equal(whatype([ 11, 22 ]), 'array');
tap.equal(whatype(function(){}), 'function');
tap.equal(whatype(() => {}), 'function');
tap.equal(whatype(new Date()), 'date');
tap.equal(whatype(new Error()), 'error');
tap.equal(whatype(new ReferenceError()), 'error');
tap.equal(whatype(new EvalError()), 'error');
tap.equal(whatype(new TypeError()), 'error');
tap.equal(whatype(new URIError()), 'error');
tap.equal(whatype(new RangeError()), 'error');
tap.equal(whatype(new SyntaxError()), 'error');
tap.equal(whatype(new Map()), 'map');
tap.equal(whatype(new WeakMap()), 'weak-map');
tap.equal(whatype(new Set()), 'set');
tap.equal(whatype(new WeakSet()), 'weak-set');
tap.equal(whatype(new Float32Array()), 'typed-array');
tap.equal(whatype(new Float64Array()), 'typed-array');
tap.equal(whatype(new Int16Array()), 'typed-array');
tap.equal(whatype(new Int32Array()), 'typed-array');
tap.equal(whatype(new Int8Array()), 'typed-array');
tap.equal(whatype(new Uint16Array()), 'typed-array');
tap.equal(whatype(new Uint32Array()), 'typed-array');
tap.equal(whatype(new Uint8Array()), 'typed-array');
tap.equal(whatype(new ArrayBuffer(10)), 'array-buffer');
tap.equal(whatype(new DataView(new ArrayBuffer())), 'data-view');
tap.equal(whatype(new Promise(() => {})), 'promise');
